import type { LibraryChoice, MaterialId } from './filamentLibrary'
import { findFilament, materialName } from './filamentLibrary'
import { colorShares } from './colorShare'
import type { RGB } from './types'

/**
 * Shopping list: every distinct filament the current palette actually uses,
 * with brand / material / color and where it is used. Slots share a spool
 * when two bands reference the same filament id, so the list is deduped and
 * aggregated — one row per spool you need to buy, not one per band.
 */

export interface ShoppingItem {
  /** Filament composite id (`brand:material:colorId`). */
  id: string
  brandName: string
  materialId: MaterialId
  material: string
  /** Catalog color name in the requested language. */
  colorName: string
  hex: string
  rgb: RGB
  /** Palette band indexes (0-based, print order) that use this spool. */
  bands: number[]
  /** Combined share of the print area across all bands using it, %. */
  areaPercent: number
}

/**
 * Build the list from the current assignments and index map. `lang` picks
 * the color-name spelling; unassigned slots and filaments that were since
 * removed from the library are skipped (they cannot be bought).
 */
export function shoppingList(
  assignments: (string | null)[],
  indexMap: Uint8Array | null,
  lang: 'en' | 'ru',
): ShoppingItem[] {
  const shares = indexMap
    ? colorShares(indexMap, assignments.length)
    : assignments.map((_, index) => ({ index, share: 0, percent: 0 }))

  const byId = new Map<string, ShoppingItem>()
  for (let i = 0; i < assignments.length; i++) {
    const id = assignments[i]
    if (!id) continue
    const f: LibraryChoice | undefined = findFilament(id)
    if (!f) continue
    const existing = byId.get(id)
    if (existing) {
      existing.bands.push(i)
      existing.areaPercent += shares[i]?.percent ?? 0
      continue
    }
    byId.set(id, {
      id,
      brandName: f.brandName,
      materialId: f.materialId,
      material: materialName(f.materialId),
      colorName: lang === 'ru' ? f.color.nameRu : f.color.nameEn,
      hex: f.color.hex,
      rgb: { ...f.color.rgb },
      bands: [i],
      areaPercent: shares[i]?.percent ?? 0,
    })
  }
  // Rounding: two halves of one spool can sum to 99.9/100.1 — snap near-integers.
  for (const item of byId.values()) {
    item.areaPercent = Math.round(item.areaPercent * 10) / 10
  }
  return [...byId.values()]
}

/** How many slots have no filament assigned — 0 means the list is complete. */
export function unassignedCount(assignments: (string | null)[]): number {
  return assignments.filter((id) => !id).length
}

const LINE = '────────────────────────────────────────'

/** Render the plain-text shopping list (the downloaded file body). */
export function formatShoppingList(
  items: ShoppingItem[],
  opts: { unassigned: number; lang: 'en' | 'ru'; header: string },
): string {
  const t = opts.lang === 'ru' ? TEXT_RU : TEXT_EN
  const lines: string[] = [opts.header, LINE, '']
  if (items.length === 0) {
    lines.push(t.empty)
  } else {
    items.forEach((item, i) => {
      lines.push(`${i + 1}. ${item.brandName} · ${item.material} · ${item.colorName}`)
      lines.push(`   ${t.hex}: ${item.hex}   ${t.area}: ${item.areaPercent.toFixed(1)}%`)
      lines.push(`   ${t.bands}: ${item.bands.map((b) => `#${b + 1}`).join(', ')}`)
      lines.push('')
    })
  }
  if (opts.unassigned > 0) {
    lines.push(`⚠ ${t.unassigned.replace('{n}', String(opts.unassigned))}`)
    lines.push('')
  }
  lines.push(LINE)
  lines.push(t.footer)
  return lines.join('\n')
}

const TEXT_EN = {
  empty: 'No filaments assigned yet — pick spools in the palette panel first.',
  hex: 'Hex',
  area: 'Area',
  bands: 'Used by bands',
  unassigned: '{n} color(s) have no filament assigned and are not listed.',
  footer: 'Generated by HueForge Web',
}

const TEXT_RU = {
  empty: 'Филаменты не назначены — выберите катушки в панели палитры.',
  hex: 'Цвет',
  area: 'Площадь',
  bands: 'Полосы',
  unassigned: '{n} цвет(ов) без назначенного филамента не включены в список.',
  footer: 'Создано HueForge Web',
}
